#!/bin/bash

FLAGS="-Os -s USE_SDL_GFX=2 -s USE_ZLIB=1 -s USE_SDL=2 -s USE_SDL_MIXER=2 --preload-file data/ -s ASYNCIFY=1 "
make  clean
make  distclean
emmake make  \
LDFLAGS_native="$FLAGS" \
CC_native=emcc  \
EXE_native=index.html \
CFLAGS_native="$FLAGS"