#!/bin/bash

#FLAGS="-s USE_SDL=2 -s USE_SDL_TTF=2 -s USE_SDL_MIXER=2 -s ASYNCIFY=1 "
make clean
make
#make \
#SDL_INCLUDE="$FLAGS" \
#SDL_CFG_native=SDL_INCLUDE="$FLAGS" \
#CC_native=emcc \
#CFLAGS_native="$FLAGS" \
#BINARY=newkind

#emcc \
#	datafilebank.c SDL2_gfxPrimitives.c SDL2_rotozoom.c sdl.c main.c docked.c elite.c intro.c planet.c shipdata.c shipface.c sound.c space.c swat.c threed.c vector.c random.c trade.c options.c stars.c missions.c pilot.c file.c keyboard.c \
#	-s USE_SDL=2\
#	-s USE_SDL_IMAGE=2 \
#	-s USE_SDL_MIXER=2 \
#	-s USE_SDL_TTF=2 \
#	-s USE_SDL_GFX=2 \
#	--preload-file data/ \
#	-s ASYNCIFY=1 \
#	-s WASM=1 \
#	-s ALLOW_MEMORY_GROWTH=1 \
#	-s FORCE_FILESYSTEM=1 \
#	-o newkind.html