#!/bin/bash
#-s USE_ZLIB=1 -s USE_SDL_GFX=2  -s USE_SDL_TTF=2

FLAGS="-Os -s USE_SDL=2 -s USE_SDL_MIXER=2 --preload-file data/ -s ASYNCIFY=1 "
make -f Makefile_html clean
make -f Makefile_html distclean
emmake make -f Makefile_html \
LDFLAGS_native="$FLAGS" \
CC_native=emcc  \
EXE_native=index.html \
CFLAGS_native="$FLAGS"